version: "2"
services:
  app:
    container_name: app
    restart: always
    build: .
    volumes: 
      - ./:/usr/src/app/
    ports:
      - ${PORT}:${PORT}
    links:
      - mongo

  mongo:
    container_name: mongo
    image: mongo
    volumes:
      - ./data:/data/db
    ports:
      - "${MONGO_PORT}:${MONGO_PORT}"
  
  