version: "2"
services:
  mongo:
    container_name: mongo
    image: mongo
    volumes:
      - ./data:/data/db
    ports:
      - "${MONGO_PORT}:${MONGO_PORT}"
  app:
    container_name: app
    restart: always
    build: .
    ports:
      - ${PORT}:${PORT}
    links:
      - mongo
  